apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbox-deployment
  labels:
    app: bbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bbox
    spec:
      containers:
      - name: bbox-container
        image: eu.gcr.io/genuine-grid-218613/bbox:alpha
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: bbox-port
        volumeMounts:
        - name: testd
          mountPath: "/data/packages"
          readOnly: false
      volumes:
      - name: testd
        persistentVolumeClaim:
          claimName: test-disk
